name: Update CrewAI Job Listings

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome and ChromeDriver
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        rm ~/chromedriver_linux64.zip
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run job scraper
      env:
        PYTHONUNBUFFERED: 1
      run: |
        python job_scraper.py || { echo "Job scraper failed"; exit 1; }

    - name: Update Discourse
      env:
        DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
        DISCOURSE_USERNAME: ${{ secrets.DISCOURSE_USERNAME }}
        DISCOURSE_URL: ${{ secrets.DISCOURSE_URL }}
        DISCOURSE_CATEGORY_ID: ${{ secrets.DISCOURSE_CATEGORY_ID }}
      run: python discourse_poster.py || { echo "Discourse update failed"; exit 1; }

    - name: Commit changes
      id: commit
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add job_listings.xlsx
        git diff --quiet && git diff --staged --quiet || git commit -m "update: Job listings updated [skip ci]"
        echo "::set-output name=changes_made::true" || echo "::set-output name=changes_made::false"

    - name: Push changes
      if: steps.commit.outputs.changes_made == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
