name: Update CrewAI Job Listings

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        
    - name: Run job scraper
      run: python job_scraper.py
        
    - name: Update Discourse
      env:
        DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
        DISCOURSE_USERNAME: ${{ secrets.DISCOURSE_USERNAME }}
        DISCOURSE_URL: ${{ secrets.DISCOURSE_URL }}
        DISCOURSE_CATEGORY_ID: ${{ secrets.DISCOURSE_CATEGORY_ID }}
      run: python discourse_poster.py